## Import Libraries

In [2]:
import numpy as np
import pandas as pd

## Load Dataset

In [5]:
df=pd.read_csv("fake_job_postings.csv")
df

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0
17878,17879,Graphic Designer,"NG, LA, Lagos",NaN,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0

## Number of Rows and Columns

In [7]:
df.shape

(17880, 18)

## Check for Duplicates

In [11]:
df.duplicated().sum()

0

## Check For Missing Values

In [13]:
df.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

## Missing Values Percentage

In [19]:
print((df.isnull().sum())/len(df)*100)

job_id                  0.000000
title                   0.000000
location                1.935123
department             64.580537
salary_range           83.959732
company_profile        18.501119
description             0.005593
requirements           15.078300
benefits               40.335570
telecommuting           0.000000
has_company_logo        0.000000
has_questions           0.000000
employment_type        19.412752
required_experience    39.429530
required_education     45.329978
industry               27.421700
function               36.101790
fraudulent              0.000000
dtype: float64

## Fill Missing Values

In [41]:
df.fillna({'location':"Unknown"},inplace=True)
df.fillna({'department':'Not Specified'},inplace=True)
df.fillna({'company_profile':'Not Available'},inplace=True)
df.fillna({'requirements':'Not Specified'},inplace=True)
df.fillna({'benefits':'Not Provided'},inplace=True)
df.fillna({'employment_type':'Not Specified'},inplace=True)
df.fillna({'required_experience':'Not Specified'},inplace=True)
df.fillna({'required_education':'Not Specified'},inplace=True)
df.fillna({'industry':'Not Specified'},inplace=True)
df.fillna({'function':'Not Specified'},inplace=True)
df.fillna({'description':'Not Provided'},inplace=True)

## Check For Missing Values

In [43]:
df.isnull().sum()

job_id                     0
title                      0
location                   0
department                 0
salary_range           15012
company_profile            0
description                0
requirements               0
benefits                   0
telecommuting              0
has_company_logo           0
has_questions              0
employment_type            0
required_experience        0
required_education         0
industry                   0
function                   0
fraudulent                 0
dtype: int64

## Verfify Datatype

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17880 non-null  object
 3   department           17880 non-null  object
 4   salary_range         2868 non-null   object
 5   company_profile      17880 non-null  object
 6   description          17880 non-null  object
 7   requirements         17880 non-null  object
 8   benefits             17880 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      17880 non-null  object
 13  required_experience  17880 non-null  object
 14  required_education   17880 non-null  object
 15  industry             17880 non-null  object
 16  function             17880 non-null  object
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

## Formatting

In [53]:
df['title']=df['title'].str.strip()
df['location']=df['location'].str.strip()
df['department']=df['department'].str.strip()
df['company_profile']=df['company_profile'].str.strip()
df['description']=df['description'].str.strip()
df['salary_range']=df['salary_range'].str.strip()
df['requirements']=df['requirements'].str.strip()
df['benefits']=df['benefits'].str.strip()
df['employment_type']=df['employment_type'].str.strip()
df['required_experience']=df['required_experience'].str.strip()
df['required_education']=df['required_education'].str.strip()
df['industry']=df['industry'].str.strip()
df['function']=df['function'].str.strip()

In [55]:
df

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,Not Provided,0,1,0,Other,Internship,Not Specified,Not Specified,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,Not Specified,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",Not Specified,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,Not Provided,0,1,0,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",Not Specified,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,Not Specified,Computer Software,Sales,0
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",Not Specified,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,Not Provided,0,0,0,Full-time,Not Specified,Not Specified,Not Specified,Not Specified,0
17878,17879,Graphic Designer,"NG, LA, Lagos",Not Specified,NaN,Not Available,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,Not Provided,0,1,1,Full-time,Mid-Senior level,Not Specified,Computer Software,Engineering,0

## Check for unique Values

In [58]:
df['employment_type'].unique()

array(['Other', 'Full-time', 'Not Specified', 'Part-time', 'Contract',
       'Temporary'], dtype=object)

In [60]:
df['industry'].unique()

array(['Not Specified', 'Marketing and Advertising', 'Computer Software',
       'Hospital & Health Care', 'Online Media',
       'Information Technology and Services', 'Financial Services',
       'Management Consulting', 'Events Services', 'Internet',
       'Facilities Services', 'Consumer Electronics',
       'Telecommunications', 'Consumer Services', 'Construction',
       'Oil & Energy', 'Education Management', 'Building Materials',
       'Banking', 'Food & Beverages', 'Food Production',
       'Health, Wellness and Fitness', 'Insurance', 'E-Learning',
       'Cosmetics', 'Staffing and Recruiting',
       'Venture Capital & Private Equity', 'Leisure, Travel & Tourism',
       'Human Resources', 'Pharmaceuticals', 'Farming', 'Legal Services',
       'Luxury Goods & Jewelry', 'Machinery', 'Real Estate',
       'Mechanical or Industrial Engineering',
       'Public Relations and Communications', 'Consumer Goods',
       'Medical Practice', 'Electrical/Electronic Manufacturing',
       'Hospitality', 'Music', 'Market Research', 'Automotive',
       'Philanthropy', 'Utilities', 'Primary/Secondary Education',
       'Logistics and Supply Chain', 'Design', 'Gambling & Casinos',
       'Accounting', 'Environmental Services', 'Mental Health Care',
       'Investment Management', 'Apparel & Fashion', 'Media Production',
       'Publishing', 'Medical Devices', 'Information Services', 'Retail',
       'Sports', 'Computer Games', 'Chemicals', 'Aviation & Aerospace',
       'Business Supplies and Equipment', 'Program Development',
       'Computer Networking', 'Biotechnology',
       'Civic & Social Organization', 'Religious Institutions',
       'Warehousing', 'Airlines/Aviation', 'Writing and Editing',
       'Restaurants', 'Outsourcing/Offshoring',
       'Transportation/Trucking/Railroad', 'Wireless',
       'Investment Banking', 'Nonprofit Organization Management',
       'Libraries', 'Computer Hardware', 'Broadcast Media', 'Printing',
       'Graphic Design', 'Entertainment', 'Wholesale', 'Research',
       'Animation', 'Government Administration', 'Capital Markets',
       'Computer & Network Security', 'Semiconductors',
       'Security and Investigations', 'Architecture & Planning',
       'Maritime', 'Fund-Raising', 'Higher Education',
       'Renewables & Environment', 'Motion Pictures and Film',
       'Law Practice', 'Government Relations', 'Packaging and Containers',
       'Sporting Goods', 'Mining & Metals', 'Import and Export',
       'International Trade and Development',
       'Professional Training & Coaching', 'Textiles',
       'Commercial Real Estate', 'Law Enforcement',
       'Package/Freight Delivery', 'Translation and Localization',
       'Photography', 'Industrial Automation', 'Wine and Spirits',
       'Public Safety', 'Civil Engineering', 'Military',
       'Defense & Space', 'Veterinary', 'Executive Office',
       'Performing Arts', 'Individual & Family Services', 'Public Policy',
       'Nanotechnology', 'Museums and Institutions', 'Fishery',
       'Plastics', 'Furniture', 'Shipbuilding',
       'Alternative Dispute Resolution', 'Ranching'], dtype=object)

In [62]:
df['function'].unique

<bound method Series.unique of 0                   Marketing
1            Customer Service
2               Not Specified
3                       Sales
4        Health Care Provider
                 ...
17875                   Sales
17876     Accounting/Auditing
17877           Not Specified
17878                  Design
17879             Engineering
Name: function, Length: 17880, dtype: object>

## Validate Binary Columns

In [66]:
df['telecommuting'].value_counts()

telecommuting
0    17113
1      767
Name: count, dtype: int64

In [68]:
df['has_company_logo'].value_counts()

has_company_logo
1    14220
0     3660
Name: count, dtype: int64

In [70]:
df['has_questions'].value_counts()

has_questions
0    9088
1    8792
Name: count, dtype: int64

In [72]:
df['fraudulent'].value_counts()

fraudulent
0    17014
1      866
Name: count, dtype: int64

## Save Clean Data

In [78]:
df.to_csv("fake_job_postings_cleaned.csv",index=False)
print("Saved Successfully!")

Saved Successfully!

In [ ]:
df.to_csv("fake_job_postings_cleaned.csv", index=False)